name : deploymet exercise 1
on : push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: install dependies
              run: npm ci
            - name: lint
              run: npm run lint
            - name: test cide
              run : npm run test
            - name: build code
              run: npm run build        
