name : deploymet exercise 2
on : push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: install dependies
              run: npm ci
            - name: lint
              run: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: install dependies
              run: npm ci
            - name: test cide
              run : npm run test
    deploy:
        needs: test

        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: install dependies
              run: npm ci
            - name: build code
              run: npm run build        
